[package]
name = "ferrofluid"
description = "A Rust library for interacting with the Hyperliquid Protocol"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Copy Paste"]
license = "MIT"
repository = "https://github.com/ControlCplusControlV/ferrofluid"

[dependencies]
